"""
Configuration for Crypto Perpetual Futures Market Neutral Strategy.
Backtest period: 2022-01-01 to 2024-12-31
"""

from pathlib import Path

START_DATE = "2022-01-01"
END_DATE = "2024-12-31"
TIMEZONE = "UTC"

SYMBOLS = ["BTCUSDT", "ETHUSDT", "SOLUSDT", "BNBUSDT", "XRPUSDT", "ADAUSDT", "DOGEUSDT", "AVAXUSDT"]

REBALANCE_HOURS = 8
ALPHA_HOURS = [0, 8, 16]

ZSCORE_LOOKBACK_DAYS = 30
VOL_CHANGE_WINDOW_HOURS = 24  # crowding proxy: volume change lookback
LAMBDA_CROWDING = 1.0

K_LONG_SHORT = 3
RV_WINDOW_BARS = 48
TARGET_VOL_ANNUAL = 0.18
GROSS_LEV_CAP = 3.0
SINGLE_ASSET_CAP = 0.25
NET_EXPOSURE_CAP = 0.10

DD_GATE_1_PCT = 0.08
DD_GATE_2_PCT = 0.12
DD_FLAT_HOURS = 8
DD_LOOKBACK_HOURS = 24

TAIL_RETURN_THRESHOLD_1 = 0.02
TAIL_RETURN_THRESHOLD_2 = 0.03
TAIL_COOLDOWN_MINUTES = 45
TAIL_BAR_INTERVAL = "5m"

FEE_BPS = 3
SLIP_BPS = 2
FUNDING_HAIRCUT = 0.9

NAV0 = 1_000_000

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"
OUTPUT_DIR = PROJECT_ROOT / "output"
FIGURES_DIR = OUTPUT_DIR / "figures"
TABLES_DIR = OUTPUT_DIR / "tables"
